spring:
  main:
    allow-circular-references: true

  application:
    name: jit
  datasource:
    url: jdbc:mariadb://localhost:4306/jit
    username: root
    password: 123456
    driver-class-name:
      org.mariadb.jdbc.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  data:
    jdbc:
      dialect: maria
    redis:
      host: localhost
      port: 6379
      database: 0
      password: redis123
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          enabled: true

server:
  port: 8080
upload:
  save-path: /Users/apple/workplace/studyproject/springstudy/spring6/jit/frontend/
  base-url: http://localhost:8081/
  relative-path: img/upload/
  relative-subject-path: img/upload/subject/
  subject-pic: img/upload/subject/
  article-pic: img/upload/
deploy:
  save-path: /Users/apple/workplace/studyproject/springstudy/spring6/jit/frontend/
  subject: subject/
  article: articles/
  indexFile: js/


